/* ai.js – AI Summary (Groq) + Related Papers panel for publication detail */
'use strict';

// ── AI Summary ─────────────────────────────────────────────────────────────
async function loadAISummary(pmid) {
  const container = document.getElementById('ai-summary-container');
  if (!container) return;

  container.innerHTML = `
    <div class="ai-summary-loading">
      <div class="ai-spinner"></div>
      <span>Generating AI summary with Groq…</span>
    </div>`;

  try {
    // First check cache
    const cached = await apiFetch(`/api/ai/summarize/${pmid}`);
    if (cached.cached && cached.summary) {
      _renderAISummary(container, cached.summary, cached.model_used, true);
      return;
    }

    // Generate new summary
    const result = await apiFetch(`/api/ai/summarize/${pmid}`, { method: 'POST' });
    _renderAISummary(container, result.summary, result.model_used, false);
  } catch (e) {
    const msg = e.message || 'Unknown error';
    const isConfig = msg.toLowerCase().includes('key') || msg.toLowerCase().includes('config');
    container.innerHTML = `
      <div class="ai-summary-error">
        <span class="ai-error-icon">⚠</span>
        <div>
          <strong>${isConfig ? 'Groq Not Configured' : 'Summary Unavailable'}</strong>
          <p>${isConfig
        ? 'Add <code>GROQ_API_KEY=your_key</code> to your <code>.env</code> file to enable AI summaries.'
        : escHtml(msg)}</p>
        </div>
      </div>`;
  }
}
window.loadAISummary = loadAISummary;

function _renderAISummary(container, summaryText, model, fromCache) {
  // Convert markdown-style bold and bullets to HTML
  const formatted = summaryText
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/^• /gm, '<li>')
    .split('\n')
    .map(line => {
      if (line.startsWith('<strong>') && line.endsWith('</strong>')) {
        return `<div class="ai-section-header">${line}</div>`;
      }
      if (line.startsWith('<li>')) {
        return `<ul><li>${line.slice(4)}</li></ul>`;
      }
      return line ? `<p>${line}</p>` : '';
    })
    .join('');

  container.innerHTML = `
    <div class="ai-summary-panel">
      <div class="ai-summary-header">
        <span class="ai-brain-icon">✨</span>
        <span class="ai-summary-title">AI Research Summary</span>
        <span class="ai-model-badge">${escHtml(model || 'Groq')}</span>
        ${fromCache ? `<span class="ai-cached-badge">cached</span>` : ''}
      </div>
      <div class="ai-summary-body">${formatted}</div>
      <div class="ai-summary-footer">
        Generated by Groq · <button class="btn-link" onclick="regenerateAISummary('${container.dataset.pmid}')">↺ Regenerate</button>
      </div>
    </div>`;
  container.dataset.pmid = container.dataset.pmid || '';
}

async function regenerateAISummary(pmid) {
  if (!pmid) return;
  await loadAISummary(pmid);
}
window.regenerateAISummary = regenerateAISummary;


// ── Related Papers ─────────────────────────────────────────────────────────
async function loadRelatedPapers(pmid) {
  const container = document.getElementById('related-papers-container');
  if (!container) return;

  container.innerHTML = `
    <div class="related-loading">
      <div class="ai-spinner small"></div>
      <span>Finding related papers…</span>
    </div>`;

  try {
    const d = await apiFetch(`/api/search/similar/${pmid}?limit=5`);
    _renderRelatedPapers(container, d.similar_articles, pmid);
  } catch (e) {
    container.innerHTML = `<div style="color:var(--text-muted);font-size:12px;padding:8px">Could not load related papers</div>`;
  }
}
window.loadRelatedPapers = loadRelatedPapers;

function _renderRelatedPapers(container, papers, currentPmid) {
  if (!papers || !papers.length) {
    container.innerHTML = `<div style="color:var(--text-muted);font-size:12px;padding:8px">
      No related papers found. Generate embeddings in Data Management to enable semantic similarity.
    </div>`;
    return;
  }

  container.innerHTML = `
    <div class="related-papers-scroll">
      ${papers.map(p => `
        <div class="related-paper-card" onclick="openPubDetail_fromRelated('${p.pmid}')">
          <div class="related-paper-title">${escHtml(p.title)}</div>
          <div class="related-paper-meta">
            <span class="badge">${p.pmid}</span>
            ${p.pub_year ? `<span class="badge purple">${p.pub_year}</span>` : ''}
            <span class="similarity-badge" title="Similarity score">${Math.round(p.similarity_score * 100)}% match</span>
          </div>
          ${p.abstract_snippet ? `<div class="related-paper-snippet">${escHtml(p.abstract_snippet)}…</div>` : ''}
        </div>`).join('')}
    </div>`;
}

window.openPubDetail_fromRelated = function (pmid) {
  // Navigate to the publications page and open the article detail
  navigateTo('publications');
  setTimeout(() => {
    document.getElementById('pub-search-pmid').value = pmid;
    if (typeof runPubSearch === 'function') runPubSearch();
    setTimeout(() => {
      const card = document.querySelector(`[data-pmid="${pmid}"]`);
      if (card) card.click();
    }, 800);
  }, 150);
};


// ── Inject AI buttons into publication detail ──────────────────────────────
function injectAIButtons(pmid) {
  const pane = document.getElementById('pub-detail-pane');
  if (!pane) return;

  // Find or create the AI section
  let aiSection = pane.querySelector('.detail-section.ai-actions');
  if (aiSection) {
    aiSection.dataset.pmid = pmid;
  } else {
    // Insert after the first detail-section (Abstract section typically)
    const firstSection = pane.querySelector('.detail-section');
    aiSection = document.createElement('div');
    aiSection.className = 'detail-section ai-actions';
    aiSection.dataset.pmid = pmid;
    if (firstSection) {
      firstSection.parentNode.insertBefore(aiSection, firstSection.nextSibling);
    } else {
      pane.appendChild(aiSection);
    }
  }

  aiSection.innerHTML = `
    <div class="ai-action-bar">
      <button class="btn btn-ai" id="btn-ai-summary-${pmid}"
              onclick="showAISection('${pmid}', 'summary')">
        ✨ AI Summary
      </button>
      <button class="btn btn-related" id="btn-related-${pmid}"
              onclick="showAISection('${pmid}', 'related')">
        📎 Related Papers
      </button>
    </div>
    <div id="ai-panel-${pmid}" class="ai-expandable" style="display:none">
      <div id="ai-summary-container" data-pmid="${pmid}"></div>
      <div id="related-papers-container" data-pmid="${pmid}"></div>
    </div>`;
}
window.injectAIButtons = injectAIButtons;

let _activeAISection = null;
window.showAISection = function (pmid, section) {
  const panel = document.getElementById(`ai-panel-${pmid}`);
  const summaryContainer = document.getElementById('ai-summary-container');
  const relatedContainer = document.getElementById('related-papers-container');
  if (!panel) return;

  // Toggle off if same section
  if (_activeAISection === section && panel.style.display !== 'none') {
    panel.style.display = 'none';
    _activeAISection = null;
    return;
  }

  panel.style.display = 'block';
  _activeAISection = section;

  if (section === 'summary') {
    if (summaryContainer) { summaryContainer.style.display = 'block'; summaryContainer.dataset.pmid = pmid; }
    if (relatedContainer) relatedContainer.style.display = 'none';
    loadAISummary(pmid);
  } else {
    if (relatedContainer) { relatedContainer.style.display = 'block'; relatedContainer.dataset.pmid = pmid; }
    if (summaryContainer) summaryContainer.style.display = 'none';
    loadRelatedPapers(pmid);
  }
};
